#Platform
platform :ios, '12.0'

#Frameworks
use_frameworks!

#Targets
target 'CoreDataStructures_Example' do
  pod 'CoreDataStructures', :path => '../'

  target 'CoreDataStructures_Tests' do
    inherit! :search_paths

    
  end
end
